### ISSUE TITLE
Beispiele/Usage example

### ISSUE THREAD

**Issue by eaCe** [FriendsOfREDAXO/graphql#5]
Could you provide an usage example within the readme? I just discovered the repository, i also built one once:
https://github.com/eaCe/graphql

**Comment by danielplan** [comment]
We are using GraphQLite in order to allow easier creation of GraphQL Types and Queries/Mutation. In general, the initial purpose was to create headless endpoints to access the Backend. 
Documentation will folloe after thr API was defined.

**Comment by danielplan** [comment]
I have now added an initial documentation to the README. Please note that the Addon is still "work in progress" such that the API may be extended and slightly changed in the near future.

**Comment by eaCe** [comment]
Thank you. I will give it a try this weekend.
